version: '3.8'

networks: 
    redis-compose-network:
      driver: bridge

volumes:
    redis_vol:     
     
services:
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
           
    depends_on:
      - redis
    networks:
      - redis-compose-network
    
  redis:
    image: redis:7.0.5
    restart: always
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]  
    networks:
      - redis-compose-network  
    volumes:
      - redis_vol:/data
    